name: intel_geti_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cookie_jar: ^3.0.1
  dio: ^4.0.6
  dio_smart_retry: ^1.3.2
  http_parser: ^4.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
